# Generated by Django 5.0.6 on 2024-07-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('custom_id', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
